# Copyright (c) 2025, Frappe Technologies Pvt. Ltd. and contributors
# For license information, please see license.txt

"""
Funzione AI per processare notifiche di cambio stato Lead e inviare messaggi WhatsApp.
"""

import frappe
from typing import Dict, Any, Optional
from ai_module.agents.runner import run_agent


def process_status_change_notification(payload: Dict[str, Any]):
	"""
	Processa una notifica di cambio stato e genera un messaggio WhatsApp tramite AI.
	
	Args:
		payload: Dizionario con:
			- phone: Numero di telefono del destinatario
			- context: Dati strutturati del cambio stato
			- lead_name: Nome del Lead
			- reference_doctype: Tipo documento (CRM Lead)
			- reference_name: Nome del documento
	"""
	try:
		from ..agents.logger_utils import get_resilient_logger
		logger = get_resilient_logger("ai_module.status_change")
		logger.info(f"PROCESS_STATUS_CHANGE START: payload={payload}")
		
		# Verifica che il modulo WhatsApp sia disponibile
		try:
			from .whatsapp import (
				_get_or_create_thread_for_phone,
				_send_autoreply,
				_log,
			)
		except ImportError as import_error:
			frappe.log_error(
				message=f"Errore importazione moduli WhatsApp: {str(import_error)}\n{frappe.get_traceback()}",
				title="AI Module Status Change - Import Error",
			)
			logger.error(f"Moduli WhatsApp non disponibili: {str(import_error)}")
			return
		
		phone = (payload.get("phone") or "").strip()
		context = payload.get("context", {})
		
		if not phone:
			logger.warning("No phone number provided, skipping notification")
			return
		
		# Normalizza il numero di telefono
		phone_normalized = "".join(c for c in phone if c.isdigit() or c == "+")
		if phone_normalized and not phone_normalized.startswith("+"):
			phone_normalized = "+" + phone_normalized
		
		# Ottieni o crea sessione per questo telefono
		session_id = _get_or_create_thread_for_phone(phone_normalized)
		logger.info(f"Session resolved: phone={phone_normalized} session={session_id}")
		
		# Prepara il prompt strutturato per l'AI
		ai_prompt = _build_status_change_prompt(context)
		
		# Ottieni il nome dell'agente
		from ai_module.integrations.whatsapp import get_environment, DEFAULT_AGENT_NAME
		from ai_module.integrations.whatsapp import apply_environment
		apply_environment()
		agent_name = get_environment().get("AI_AGENT_NAME") or DEFAULT_AGENT_NAME
		
		# Chiama l'AI per generare il messaggio
		result = run_agent(
			agent_or_name=agent_name,
			input_text=ai_prompt,
			session_id=session_id
		)
		
		logger.info(f"AI result type: {type(result)}")
		logger.info(f"AI result content: {result}")
		
		# Estrai il testo della risposta
		reply_text = ""
		if isinstance(result, dict):
			reply_text = (result.get("final_output") or result.get("response") or "").strip()
		elif isinstance(result, str):
			reply_text = result.strip()
		
		if reply_text:
			logger.info(f"Generated message: {reply_text[:100]}...")
			
			# Prepara il payload per l'invio WhatsApp
			# Nota: _send_autoreply usa "from" per il numero destinatario
			whatsapp_payload = {
				"from": phone_normalized,  # Destinatario del messaggio
				"message": reply_text,
				"reference_doctype": payload.get("reference_doctype", "CRM Lead"),
				"reference_name": payload.get("reference_name", payload.get("lead_name")),
				"name": None,  # Non abbiamo un messaggio WhatsApp esistente
			}
			
			# Invia il messaggio WhatsApp
			_send_autoreply(whatsapp_payload, reply_text)
			logger.info(f"Status change notification sent to {phone_normalized}")
		else:
			logger.warning("No reply text generated by AI")
		
	except Exception as e:
		frappe.log_error(
			message=frappe.get_traceback(),
			title="ai_module.integrations.status_change.process_status_change_notification",
		)
		logger.error(f"Error processing status change notification: {str(e)}")


def _build_status_change_prompt(context: Dict[str, Any]) -> str:
	"""
	Costruisce un prompt strutturato per l'AI basato sul contesto del cambio stato.
	"""
	order_number = context.get("order_number", "")
	old_status = context.get("old_status", "N/A")
	new_status = context.get("new_status", "")
	customer_name = context.get("customer_name", "Cliente")
	
	# Prompt base per cambio stato generico
	prompt_parts = [
		"Sei un assistente AI per un'azienda che gestisce ordini.",
		f"Il cliente {customer_name} ha un ordine con numero {order_number}.",
		f"Lo stato dell'ordine è cambiato da '{old_status}' a '{new_status}'.",
		"",
		"Genera un messaggio WhatsApp professionale e cortese per informare il cliente del cambio di stato.",
		"Il messaggio deve essere:",
		"- In italiano",
		"- Professionale ma amichevole",
		"- Conciso ma completo",
		"- Includere il numero d'ordine",
		"- Spiegare chiaramente il nuovo stato",
		"",
	]
	
	# Se lo stato è "Attesa Pagamento", aggiungi dettagli ordine e pagamento
	if context.get("has_order_details") and context.get("order_summary"):
		order_summary = context["order_summary"]
		payment_info = context.get("payment_info", {})
		
		prompt_parts.extend([
			"IMPORTANTE: Lo stato è 'Attesa Pagamento'. Devi includere:",
			"",
			"1. Riepilogo completo dell'ordine:",
		])
		
		# Aggiungi prodotti
		for product in order_summary.get("products", []):
			prompt_parts.append(
				f"- {product['name']}: {product['quantity']} x €{product['unit_price']:.2f} = €{product['total_price']:.2f}"
			)
		
		prompt_parts.extend([
			f"Totale: €{order_summary.get('net_total', 0):.2f}",
			"",
			"2. Informazioni per il pagamento:",
		])
		
		# Se le informazioni pagamento sono testo libero dalle impostazioni
		if payment_info.get("source") == "settings" and payment_info.get("text"):
			prompt_parts.extend([
				payment_info["text"],
				"",
				"Usa queste informazioni esattamente come fornite, formattandole in modo chiaro e professionale.",
			])
		# Altrimenti usa la struttura dati di default
		elif payment_info.get("source") == "default":
			# Aggiungi info pagamento strutturate
			if payment_info.get("bank_transfer"):
				bank = payment_info["bank_transfer"]
				prompt_parts.extend([
					"Bonifico Bancario:",
					f"- Banca: {bank['bank_name']}",
					f"- IBAN: {bank['iban']}",
					f"- SWIFT: {bank['swift']}",
					f"- Intestatario: {bank['account_holder']}",
					f"- Causale: Ordine {order_number}",
				])
			
			if payment_info.get("paypal"):
				paypal = payment_info["paypal"]
				prompt_parts.extend([
					"",
					"PayPal:",
					f"- Email: {paypal['email']}",
					f"- Nota: {paypal['note']}",
				])
			
			if payment_info.get("instructions"):
				prompt_parts.extend([
					"",
					payment_info["instructions"],
				])
		
		prompt_parts.extend([
			"",
			"3. Istruzioni chiare su come procedere con il pagamento.",
			"",
			"Assicurati di includere tutte queste informazioni nel messaggio finale.",
		])
	
	prompt_parts.extend([
		"",
		"Genera SOLO il messaggio WhatsApp, senza aggiungere spiegazioni o commenti.",
	])
	
	return "\n".join(prompt_parts)

